---
- name: Setup CloudWatch Agent
  hosts: ec2
  become: yes
  tasks:
    - name: Install CloudWatch Agent
      ansible.builtin.yum:
        name: amazon-cloudwatch-agent
        state: present

    - name: Create CloudWatch Config File
      ansible.builtin.copy:
        dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json
        content: |
          {
            "metrics": {
              "namespace": "CWAgent",
              "metrics_collected": {
                "mem": {
                  "measurement": ["mem_used_percent"],
                  "metrics_collection_interval": 60
                },
                "disk": {
                  "measurement": ["disk_used_percent"],
                  "metrics_collection_interval": 60,
                  "resources": ["*"]
                }
              }
            }
          }

    - name: Start CloudWatch Agent
      ansible.builtin.shell: |
        /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
          -a fetch-config \
          -m ec2 \
          -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json \
          -s
    
    - name: Enable Agent on boot 
      ansible.builtin.systemd:
        name: amazon-cloudwatch-agent
        state: started
        enabled: true

    - name: Check agent status
      ansible.builtin.shell: |
        /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a status
      register: status

    - name: Print status
      ansible.builtin.debug:
        msg: "{{ status.stdout }}"